import type { IconType } from "react-icons";
import {
  SiAntdesign,
  SiAxios,
  SiClickup,
  SiDocker,
  SiFigma,
  SiFramer,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGraphql,
  SiGreensock,
  SiJavascript,
  SiJira,
  SiMongodb,
  SiNextdotjs,
  SiReact,
  SiReactquery,
  SiSass,
  SiShadcnui,
  SiTailwindcss,
  SiThreedotjs,
  SiTrello,
  SiTypescript,
} from "react-icons/si";
import { TbBrandReactNative } from "react-icons/tb";

/** Maps skills.data.ts `icon` keys to their brand mark. Skills without an
 * entry here render a text monogram instead. */
export const skillIconMap: Record<string, IconType> = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  react: SiReact,
  nextjs: SiNextdotjs,
  reactNative: TbBrandReactNative,
  motion: SiFramer,
  threejs: SiThreedotjs,
  gsap: SiGreensock,
  shadcn: SiShadcnui,
  tailwind: SiTailwindcss,
  antdesign: SiAntdesign,
  sass: SiSass,
  axios: SiAxios,
  reactQuery: SiReactquery,
  graphql: SiGraphql,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  figma: SiFigma,
  docker: SiDocker,
  mongodb: SiMongodb,
  clickup: SiClickup,
  trello: SiTrello,
  jira: SiJira,
};
