import type { IconType } from "react-icons";
import {
  SiAnimedotjs,
  SiAntdesign,
  SiAxios,
  SiBootstrap,
  SiClaudecode,
  SiClickup,
  SiCursor,
  SiDocker,
  SiFigma,
  SiFramer,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGraphql,
  SiGreensock,
  SiHermes,
  SiJavascript,
  SiJira,
  SiMongodb,
  SiMui,
  SiN8N,
  SiNextdotjs,
  SiReact,
  SiReactquery,
  SiRedux,
  SiSass,
  SiShadcnui,
  SiTailwindcss,
  SiThreedotjs,
  SiTrello,
  SiTypescript
} from "react-icons/si";
import { TbBrandReactNative } from "react-icons/tb";
import SvgIcon from "../svg/openclaw.icon";

/** Maps skills.data.ts `icon` keys to their brand mark. Skills without an
 * entry here render a text monogram instead. */
export const skillIconMap: Record<string, IconType> = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  react: SiReact,
  nextjs: SiNextdotjs,
  reactNative: TbBrandReactNative,
  motion: SiFramer,
  threejs: SiThreedotjs,
  gsap: SiGreensock,
  animejs: SiAnimedotjs,
  redux: SiRedux,
  shadcn: SiShadcnui,
  tailwind: SiTailwindcss,
  bootstrap: SiBootstrap,
  mui: SiMui,
  antdesign: SiAntdesign,
  sass: SiSass,
  axios: SiAxios,
  reactQuery: SiReactquery,
  graphql: SiGraphql,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  figma: SiFigma,
  docker: SiDocker,
  mongodb: SiMongodb,
  clickup: SiClickup,
  trello: SiTrello,
  jira: SiJira,
  claude: SiClaudecode,
  n8n: SiN8N,
  hermes: SiHermes,
  openclaw: SvgIcon,
  cursor: SiCursor,
};
