import type { Metadata } from "next";
import { Bubblegum_Sans, PT_Sans } from "next/font/google";
import "./globals.css";

const primary = PT_Sans({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const secondary = Bubblegum_Sans({
  variable: "--font-secondary",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primary.variable} ${secondary.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
